name: Learning Steps

on:
  push:
    branches:
      - main

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Step1
        run: echo "Start"
      - name: Step2
        run: date
      - name: Step3
        run: hostname
      - name: Fail Step
        run: abcxyz
      - name: Step4
        run: echo "Finished"
